[tox]
envlist = py{310,311,312}, lint

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
extras = test
commands =
    pytest --basetemp={envtmpdir} {posargs}

[testenv:genconfig]
basepython = python3
sitepackages = False
commands = oslo-config-generator --config-file=tools/config-generator.conf

[testenv:lint]
basepython = python3
skip_install = true
deps =
    ruff
commands =
    ruff check haminfo tests
    ruff format --check haminfo tests

[testenv:pylint]
skip_install = true
deps =
    pyflakes
    pylint!=2.5.0
commands =
    pylint haminfo

[tool:pytest]
testpaths = tests
addopts = -v --tb=short
