# Use postgres/example user/password credentials
version: '3.1'

services:

  haminfo:
    image: hemna6969/haminfo:latest
    restart: unless-stopped
    depends_on:
        - "db"
    ports:
      - 8060:80
    volumes:
      - /opt/docker/haminfo/config:/config
    environment:
      - INIT_DB=False

  cron:
    image: hemna6969/haminfo:latest
    restart: unless-stopped
    depends_on:
        - "haminfo"
    volumes:
      - /opt/docker/haminfo/config:/config
    entrypoint: /home/haminfo/cron_entry.sh
    environment:
      - INIT_DB=False

  db:
    image: postgis/postgis:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: haminfo
      POSTGRES_USER: haminfo
      POSTGRES_PASSWORD: haminfo
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
        - "db"
    ports:
      - 8066:8080
