"""add aprs_packet table

Revision ID: 3a3e840c4d49
Revises: 93f9b60edc43
Create Date: 2025-12-15 13:36:06.832562

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision = '3a3e840c4d49'
down_revision = '93f9b60edc43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('aprs_packet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_call', sa.String(), nullable=False),
    sa.Column('to_call', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('packet_type', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location', Geography(geometry_type='POINT', spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('maidenhead', sa.String(), nullable=True),
    sa.Column('symbol', sa.CHAR(), nullable=True),
    sa.Column('symbol_table', sa.CHAR(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('object_name', sa.String(), nullable=True),
    sa.Column('object_killed', sa.Boolean(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('rain_1h', sa.Float(), nullable=True),
    sa.Column('rain_24h', sa.Float(), nullable=True),
    sa.Column('rain_since_midnight', sa.Float(), nullable=True),
    sa.Column('solar_radiation', sa.Float(), nullable=True),
    sa.Column('uv_index', sa.Integer(), nullable=True),
    sa.Column('luminosity', sa.Float(), nullable=True),
    sa.Column('snow', sa.Float(), nullable=True),
    sa.Column('telemetry_analog', sa.String(), nullable=True),
    sa.Column('telemetry_digital', sa.String(), nullable=True),
    sa.Column('telemetry_sequence', sa.Integer(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('message_ack', sa.String(), nullable=True),
    sa.Column('message_reject', sa.Boolean(), nullable=True),
    sa.Column('query_type', sa.String(), nullable=True),
    sa.Column('query_response', sa.Text(), nullable=True),
    sa.Column('third_party', sa.Text(), nullable=True),
    sa.Column('capcode', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('compressed', sa.Boolean(), nullable=True),
    sa.Column('mic_e', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_geospatial_index('idx_aprs_packet_location', 'aprs_packet', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_aprs_packet_from_call'), 'aprs_packet', ['from_call'], unique=False)
    op.create_index(op.f('ix_aprs_packet_packet_type'), 'aprs_packet', ['packet_type'], unique=False)
    op.create_index(op.f('ix_aprs_packet_received_at'), 'aprs_packet', ['received_at'], unique=False)
    op.create_index(op.f('ix_aprs_packet_timestamp'), 'aprs_packet', ['timestamp'], unique=False)
    op.create_index(op.f('ix_aprs_packet_to_call'), 'aprs_packet', ['to_call'], unique=False)
    op.alter_column('station', 'location',
               existing_type=Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               type_=Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.create_unique_constraint(None, 'weather_report', ['id'])
    op.alter_column('weather_station', 'location',
               existing_type=Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               type_=Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather_station', 'location',
               existing_type=Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               type_=Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.drop_constraint(None, 'weather_report', type_='unique')
    op.alter_column('station', 'location',
               existing_type=Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               type_=Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.drop_index(op.f('ix_aprs_packet_to_call'), table_name='aprs_packet')
    op.drop_index(op.f('ix_aprs_packet_timestamp'), table_name='aprs_packet')
    op.drop_index(op.f('ix_aprs_packet_received_at'), table_name='aprs_packet')
    op.drop_index(op.f('ix_aprs_packet_packet_type'), table_name='aprs_packet')
    op.drop_index(op.f('ix_aprs_packet_from_call'), table_name='aprs_packet')
    op.drop_geospatial_index('idx_aprs_packet_location', table_name='aprs_packet', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('aprs_packet')
    # ### end Alembic commands ###
