"""add WXRequest

Revision ID: 6c283c2e789f
Revises: 898b1497d0b2
Create Date: 2023-04-18 15:50:41.722058

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c283c2e789f'
down_revision = '898b1497d0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create sequence wx_request_id_seq")
    op.create_table('wx_request',
    sa.Column('id', sa.Integer(), sa.Sequence('wx_request_id_seq'), nullable=False, unique=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('callsign', sa.String(), nullable=True),
    sa.Column('station_callsigns', sa.String(), nullable=True),
    sa.Column('wx_station_ids', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wx_request')
    op.execute("drop sequence wx_request_id_seq")
    # ### end Alembic commands ###
