"""Create Request Table

Revision ID: 96858633a9ae
Revises: 0146a00337db
Create Date: 2021-12-28 12:21:24.704183

"""
from alembic import op
import sqlalchemy as sa
import imp


# revision identifiers, used by Alembic.
revision = '96858633a9ae'
down_revision = '0146a00337db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    alembic_helpers = imp.load_source('alembic_helpers', (
        op.get_context().script.dir + '/alembic_helpers.py'))
    if alembic_helpers.table_does_not_exist('request'):
        print("Creating sequence request_id_seq")
        op.execute("create sequence request_id_seq")
        print("Creating table request")
        op.create_table('request',
        sa.Column('id', sa.Integer(), sa.Sequence('request_id_seq'), nullable=False),  # noqa
        sa.Column('created', sa.Date(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('band', sa.String(), nullable=True),
        sa.Column('filters', sa.String(), nullable=True),
        sa.Column('count', sa.Integer(), nullable=True),
        sa.Column('callsign', sa.String(), nullable=True),
        sa.Column('stations', sa.String, nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    op.execute("drop sequence request_id_seq")
    # ### end Alembic commands ###
