name: Docker Image CI

on:
  push:
    branches:
        - "**"
    tags:
        - "v*.*.*"
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get Branch Name
      id: branch-name
      uses: tj-actions/branch-names@v8
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker HUB
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}:docker"
        platforms: linux/amd64,linux/arm64
        file: ./Dockerfile
        push: true
        tags: |
          hemna6969/haminfo:${{ steps.branch-name.outputs.current_branch }}
          hemna6969/haminfo:latest
